FROM python:3.10-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ./app .

ENV APT_SALUTATION=""
ENV APT_FIRST_NAME=""
ENV APT_LAST_NAME=""
ENV APT_MAIL=""
ENV APT_PHONE=""
ENV APT_MAX_DAYS_AHEAD="14"

ENTRYPOINT python3 main.py